try:
    print("Inside The Try Block!!!")
    print(y)

except:
    print("Inside The Except Block!!!")
